apiVersion: apps/v1
kind: Deployment
metadata:
  name: gagan1
  namespace: gitops
  labels:
    app: gitops
spec:
  selector:
    matchLabels:
      app: gitops
  replicas: 2 
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: sainigagan29/final:1.0
        # imagePullPolicy : Always
        ports:
        - containerPort: 8000
     